.PHONY: clean All

All:
	@echo "----------Building project:[ assignment1b - Debug ]----------"
	@cd "assignment1b" && "$(MAKE)" -f  "assignment1b.mk"
clean:
	@echo "----------Cleaning project:[ assignment1b - Debug ]----------"
	@cd "assignment1b" && "$(MAKE)" -f  "assignment1b.mk" clean
